name: Update funds.json nightly

on:
  schedule:
    - cron: "30 12 * * *"   # 12:30 UTC = 7:30 AM Chicago during CDT
  workflow_dispatch: {}
  push:
    paths:
      - ".github/workflows/update-funds.yml"

permissions:
  contents: write

jobs:
  refresh:
    runs-on: windows-latest   # ok for Selenium + setup-chrome
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Chrome (for Selenium)
        uses: browser-actions/setup-chrome@v1

      - name: Show tool versions
        shell: pwsh
        run: |
          python --version
          chrome --version

      - name: Install Python deps
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager pandas requests lxml beautifulsoup4

      - name: Run scraper -> public/funds.json
        shell: pwsh
        run: |
          python .\batch_export_json.py
          if (-not (Test-Path .\public\funds.json)) {
            throw "public\funds.json not found after scraper run"
          }

      - name: Commit & push if changed
        shell: pwsh
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .\public\funds.json
          if (-not (git diff --cached --quiet)) {
            git commit -m "chore: nightly data refresh"
            git push
          } else {
            echo "No changes detected"
          }
