name: Update funds.json nightly

on:
  schedule:
    - cron: "30 12 * * *"   # 12:30 UTC = 7:30 AM Chicago during CDT
  workflow_dispatch: {}
  push:
    paths:
      - ".github/workflows/update-funds.yml"

permissions:
  contents: write

jobs:
  refresh:
    runs-on: windows-latest   # ok for Selenium + setup-chrome
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python
