name: Update funds.json nightly

on:
  schedule:
    - cron: "30 12 * * *"      # 7:30 AM America/Chicago
  workflow_dispatch: {}
  push:
    paths:
      - ".github/workflows/update-funds.yml"
      - "ishares_fixed_income_scraper.py"
      - "batch_export_json.py"

permissions:
  contents: write

jobs:
  refresh:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Chrome (for Selenium)
        uses: browser-actions/setup-chrome@v1

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager pandas requests lxml beautifulsoup4

      - name: Ensure public/ exists
        shell: pwsh
        run: New-Item -ItemType Directory -Force -Path public | Out-Null

      # 👇 run the scraper first to produce the CSVs in the workspace
      - name: Run scraper (creates ishares_fixed_income_metrics_*.csv)
        shell: pwsh
        run: python .\ishares_fixed_income_scraper.py

      # 👇 then convert the latest CSV into public/funds.json (ALL rows)
      - name: Export to funds.json
        run: python .\batch_export_json.py

      - name: Show result size
        shell: pwsh
        run: |
          Write-Host "funds.json size: " (Get-Item .\public\funds.json).Length "bytes"
          Write-Host "First lines:"; Get-Content .\public\funds.json -TotalCount 5

      - name: Commit & push if changed (rebase-safe)
        shell: pwsh
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .\public\funds.json
          if (-not (git diff --cached --quiet)) {
            git commit -m "chore: refresh funds.json"
            $max=3
            for ($i=1; $i -le $max; $i++) {
              git pull --rebase origin $env:GITHUB_REF_NAME || exit 1
              git push && exit 0
            }
            throw "Failed to push after $max attempts"
          } else {
            echo "No changes to commit"
          }
