name: Update funds.json nightly

on:
  schedule:
    - cron: "30 12 * * *"      # 7:30 AM America/Chicago
  workflow_dispatch: {}
  push:
    paths:
      - ".github/workflows/update-funds.yml"
      - "ishares_fixed_income_scraper.py"
      - "batch_export_json.py"

permissions:
  contents: write

jobs:
  refresh:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Chrome (for Selenium)
        uses: browser-actions/setup-chrome@v1

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager pandas requests lxml beautifulsoup4

      - name: Ensure public/ exists
        shell: pwsh
        run: New-Item -ItemType Directory -Force -Path public | Out-Null

      # 1) Run the scraper to create ishares_fixed_income_metrics_*.csv
      - name: Run scraper (writes CSVs)
        shell: pwsh
        run: python .\ishares_fixed_income_scraper.py

      # 2) If your script saved CSVs outside the repo (e.g., C:\home\...), copy them back
      - name: Locate metrics CSVs and copy to workspace if needed
        shell: pwsh
        run: |
          $found = $false
          $ws = $env:GITHUB_WORKSPACE
          # search where they’re likely to land
          foreach ($root in @($ws, 'C:\home', 'D:\a')) {
            if (Test-Path $root) {
              Get-ChildItem -Path $root -Recurse -Filter 'ishares_fixed_income_metrics_*.csv' -ErrorAction SilentlyContinue |
                ForEach-Object {
                  Write-Host "Found: $($_.FullName)"
                  if ($_.DirectoryName -ne $ws) {
                    Copy-Item $_.FullName $ws -Force
                    Write-Host "Copied to workspace: $ws"
                  }
                  $found = $true
                }
            }
          }
          if (-not $found) {
            Write-Error "No metrics CSV found after scraping."
            exit 1
          }
          Write-Host "Metrics present in workspace:"
          Get-ChildItem -Path $ws -Filter 'ishares_fixed_income_metrics_*.csv'

      # 3) Convert the latest CSV to public/funds.json (ALL rows)
      - name: Export to funds.json
        run: python .\batch_export_json.py

      - name: Show result size
        shell: pwsh
        run: |
          Write-Host "funds.json size: " (Get-Item .\public\funds.json).Length "bytes"
          Get-Content .\public\funds.json -TotalCount 5

      - name: Commit & push if changed (rebase-safe)
        shell: pwsh
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .\public\funds.json
          if (-not (git diff --cached --quiet)) {
            git commit -m "chore: refresh funds.json"
            for ($i=1; $i -le 3; $i++) {
              git pull --rebase origin $env:GITHUB_REF_NAME || exit 1
              git push && exit 0
            }
            throw "Failed to push after 3 attempts"
          } else {
            echo "No changes to commit"
          }
