name: Update funds.json nightly

on:
  schedule:
    # 12:30 UTC ≈ 7:30 AM America/Chicago
    - cron: "30 12 * * *"
  workflow_dispatch: {}

permissions:
  contents: write   # allow commits/pushes from the workflow

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Chrome (for Selenium)
        uses: browser-actions/setup-chrome@v1

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager pandas requests lxml beautifulsoup4

      # ⬇️ Pick the script that writes ./public/funds.json inside THIS repo
      # If your in-repo script is `ishares_fixed_income_scraper.py`, keep this:
      - name: Run scraper
        run: |
          python ishares_fixed_income_scraper.py
          test -f public/funds.json

      # If instead your in-repo script is `blake.py`, use this step instead:
      # - name: Run scraper
      #   run: |
      #     python blake.py
      #     test -f public/funds.json

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add public/funds.json
            git commit -m "chore: nightly data refresh"
            git push
          else
            echo "No changes detected"
          fi
