name: Update funds.json nightly

on:
  schedule:
    - cron: "30 12 * * *"   # 7:30 AM America/Chicago
  workflow_dispatch: {}      # enables the "Run workflow" button
  push:
    paths:
      - ".github/workflows/update-funds.yml"  # re-run when this file changes

permissions:
  contents: write            # allow the workflow to commit/push

jobs:
  refresh:
    runs-on: windows-latest  # safer for Windows-style scripts

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Chrome (for Selenium)
        uses: browser-actions/setup-chrome@v1

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager pandas requests lxml beautifulsoup4

      - name: Make sure output folder exists
        shell: pwsh
        run: New-Item -ItemType Directory -Force -Path public | Out-Null

      # 🔽 Pick the script that writes ./public/funds.json inside THIS repo
      - name: Run scraper
        shell: pwsh
        run: |
          if (Test-Path .\ishares_fixed_income_scraper.py) {
            python .\ishares_fixed_income_scraper.py
          } elseif (Test-Path .\blake.py) {
            python .\blake.py
          } else {
            throw "No scraper script found (expected ishares_fixed_income_scraper.py or blake.py)"
          }
          if (-not (Test-Path .\public\funds.json)) {
            throw "public\funds.json not found after scraper run"
          }

      - name: Commit & push if changed
        shell: pwsh
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .\public\funds.json
          if (-not (git diff --cached --quiet)) {
            git commit -m "chore: nightly data refresh"
            git push
          } else {
            echo "No changes detected"
          }
